TalEliyahu/TalEliyahu/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TalEliyahu;

namespace TalEliyahu
{
    public class StudentsController : Controller
    {
        private TalDbContext db = new TalDbContext();

        // GET: Students
        public ActionResult Index()
        {
            return View(db.Students.ToList());
        }

        // GET: Students/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // GET: Students/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StudentIndex,StudentName,StudentId,StudentPassword,StudentEmail")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Students.Add(student);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(student);
        }

        // GET: Students/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StudentIndex,StudentName,StudentId,StudentPassword,StudentEmail")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Entry(student).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(student);
        }

        // GET: Students/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Student student = db.Students.Find(id);
            db.Students.Remove(student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TalEliyahu/TalEliyahu/Views/Admin/Admin.cshtml
@section modelORusing{
    @using TalEliyahu
    @using System.Collections.Generic;
    @model IEnumerable<object>
}
    @{
        List<TalEliyahu.Student> lstStudents = Model.ToList()[0] as List<TalEliyahu.Student>;
        List<TalEliyahu.User> lstUsers = Model.ToList()[1] as List<TalEliyahu.User>;
    }

<div class="wrap">
    <div class="container">
        <section>
            <div class="row">
                <div style="text-align:right">

                    <!--panel-Student---------------------------------------------------------------->
                    <div class="panel-group" role="tablist">
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="collapseListGroupHeading1">
                                <h4 class="panel-title">
                                    <a href="#collapseListGroup1" class="collapsed" role="button" data-toggle="collapse" aria-expanded="false" aria-controls="collapseListGroup1"> @ViewBag.AllStudents : סך הכל תלמידים </a>
                                </h4>
                            </div>
                            <div class="panel-collapse collapse" role="tabpanel" id="collapseListGroup1" aria-labelledby="collapseListGroupHeading1" aria-expanded="false" style="height: 0px;">
                                <!--Table-->
                                <table class="table table-hover" style="text-align:right;">
                                    <thead>
                                        <tr>
                                            <th></th>
                                            <th>אימייל</th>
                                            <th>סיסמה</th>
                                            <th>תעודת זהות</th>
                                            <th>שם</th>
                                            <th>#</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (lstStudents != null)
                                        {
                                            foreach (var s in lstStudents)
                                            {
                                                <tr>
                                                    <td>
                                                        @Html.ActionLink("עריכה", "Edit", new { id = s.StudentIndex }) |
                                                        @Html.ActionLink("פרטים", "Details", new { id = s.StudentIndex }) |
                                                        @Html.ActionLink("מחיקה", "Delete", new { id = s.StudentIndex })
                                                    </td>
                                                    <td>@Html.DisplayFor(modelItem => s.StudentEmail)</td>
                                                    <td>@Html.DisplayFor(modelItem => s.StudentName)</td>
                                                    <td>@s.StudentPassword.ToString()</td>
                                                    <td>@s.StudentId.ToString()</td>
                                                    <td>@s.StudentIndex.ToString()</td>
                                                </tr>
                                            }
                                        }
                                        else
                                        {
                                            <tr>אין עדיין תלמידים במערכת</tr>
                                        }
                                    </tbody>
                                </table>
                                @Html.ActionLink("הוספת תלמיד/ה", "Create", "Students")
                                <br />
                                <br />
                                <br />
                                <!--EndTable-->                           
                            </div>
                        </div>
                    </div>
                    <!--//panel-Student-------------------------------------------------------------->
                    <!--panel-User---------------------------------------------------------------->
                    <div class="panel-group" role="tablist">
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="collapseListGroupHeading1">
                                <h4 class="panel-title">
                                    <a href="#collapseListGroup2" class="collapsed" role="button" data-toggle="collapse" aria-expanded="false" aria-controls="collapseListGroup2">@ViewBag.AllUsers : סך הכל יוזרים</a>
                                </h4>
                            </div>
                            <div class="panel-collapse collapse" role="tabpanel" id="collapseListGroup2" aria-labelledby="collapseListGroupHeading2" aria-expanded="false" style="height: 0px;">
                                <!--Table-->
                                <table class="table table-hover" style="text-align:right">
                                    <thead>
                                        <tr>
                                            <th></th>
                                            <th>אימייל</th>
                                            <th>שם</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (lstUsers != null)
                                        {
                                            foreach (var u in lstUsers)
                                            {
                                                <tr>
                                                    <td onclick="LoadPartialView()">
                                                        @*@Html.ActionLink("מחיקה", "_Delete", new { id = u.UserIndex })*@
                                                        מחיקה
                                                    </td>
                                                    <td>@u.UsertEmail.ToString()</td>
                                                    <td>@u.UserName.ToString()</td>
                                                </tr>
                                            }
                                        }
                                        else
                                        {
                                            <tr>אין עדיין יוזרים רשומים במערכת</tr>
                                        }
                                    </tbody>
                                </table>
                                <!--EndTable-->                             
                            </div>
                        </div>
                    </div>
                    <!--//panel-User-------------------------------------------------------------->
                    <hr />
                    <br />
                </div>

                <div id="dialogBox">
                    @Html.Partial("ghfghgf")
                </div>

 
                <div class="span4">
                    <h2 class="title"><span>מלל מלל</span></h2>
                    <p style="text-align:right">מלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מלל</p>
                    <p style="text-align:right">מלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מלל</p>
                </div>
                <div class="span4">
                    <h2 class="title"><span>מלל מלל</span></h2>
                    <p style="text-align:right">מלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מלל</p>
                    <p style="text-align:right">מלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מלל</p>
                </div>
                <div class="span4">
                    <h2 class="title"><span>מלל מלל מלל</span></h2>
                    <p style="text-align:right">מלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מלל</p>
                    <p style="text-align:right">מלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מלל</p>
                </div>
            </div>
        </section>
        <section>
            <h2 class="title"><span>מלל מלל</span></h2>
            <p style="text-align:right">מלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מלל</p>
            <div class="row">
                <div class="span3">
                    <div class="profile">
                        <img alt="" src="~/images/team1.jpg">
                        <h4>מלל מלל</h4>
                        <div class="profile_title">מלל מלל</div>
                        <p>מלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מלל</p>
                    </div>
                </div>
                <div class="span3">
                    <div class="profile">
                        <img alt="" src="~/images/team2.jpg">
                        <h4>מלל מלל</h4>
                        <div class="profile_title">מלל</div>
                        <p>מלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מלל</p>
                    </div>
                </div>
                <div class="span3">
                    <div class="profile">
                        <img alt="" src="~/images/team3.jpg">
                        <h4>מלל מלל</h4>
                        <div class="profile_title">מלל מלל</div>
                        <p>מלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מלל</p>
                    </div>
                </div>
                <div class="span3">
                    <div class="profile">
                        <img alt="" src="~/images/team4.jpg">
                        <h4>מלל מלל</h4>
                        <div class="profile_title">מלל</div>
                        <p>מלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מללמלל מלל</p>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

@section ScriptEnd
{
    <script type="text/javascript">
        $(document).ready(function () {

            $("li").removeClass("current");
            $("#liStudents").addClass("current");

         });
</script>

<script>
    function LoadPartialView() {
        //Make it a dialog box. Note that you don't have to do this every time the button is called, so you might want to make it dialog on document ready or something.

        $("#dialogBox").dialog({
            draggable: false,
            resizable: false,
            height: "auto",
            width: 400,
            modal: true,
            buttons: {
                "ביטול": function () {
                    $(this).dialog("close");
                    $("#dialogBox").hide();
                },
                "מחיקה": function () {
                    $(this).dialog("close");
                    $("#dialogBox").hide();
                }
            }
        });

        $.ajax({
            url: 'SomeActionName',
            type: 'post',
            success: function (html) {
                $('#dialogBox').html(html);
                $("#dialogBox").dialog("show"); //This could also be dialog("open") depending on the version of jquery ui.
            }
        });
    }
</script>



}

TalEliyahu/TalEliyahu/Views/Admin/_Delete.cshtml
@model TalEliyahu.User

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>User</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.UserName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UsertEmail)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UsertEmail)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div>
                <input type="submit" value="Delete" /> |
                @Html.ActionLink("Back to List", "Admin")
            </div>
        }
    </div>