TalEliyahu/TalEliyahu/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TalEliyahu
{
    public class ArticlesController : Controller
    {
        // GET: Articles
        public ActionResult Articles()
        {
            return View();
        }

        // GET: Peaceful
        public ActionResult Peaceful()
        {
            return View();
        }
    }
}

TalEliyahu/TalEliyahu/Controllers/MyStoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TalEliyahu
{
    public class MyStoryController : Controller
    {
        // GET: MyStory
        public ActionResult MyStory()
        {
            return View();
        }
    }
}

TalEliyahu/TalEliyahu/Controllers/RidingStylesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TalEliyahu
{
    public class RidingStylesController : Controller
    {
        // GET: RidingStyles
        public ActionResult RidingStyles()
        {
            return View();
        }

        public ActionResult SpiritualRiding()
        {
            return View();
        }
    }
}

TalEliyahu/TalEliyahu/Views/MyStory/MyStory.cshtml
<div class="container">
    <div class="wrap">
        <div class="container content_bg">
            <section>
                <div class="row">
                    <div class="span8">
                        <h2 class="title"><span>,קוראים לי טל אליהו</span></h2>
                        <p style="text-align:right; font-size:medium; margin-bottom:18px;" dir='rtl'>
                            ואני בת 25. לא התחלתי לרכב מגיל צעיר כמו רב הרוכבים...<br />
                            אני נחשפתי לעולם הסוסים בגיל מאוחר יחסית ובהתחלה לא הבנתי בכלל לאן ולמה אני נכנסת.<br />
                            לא הבנתי שהחיים שלי עומדים להתהפך ב-180 מעלות ושברגע זה החיים שלי &quot;ניצלו&quot;.<br />
                            <br />
                            <img src="~/images/gallery/MyStory/1.jpg" />
                            <br />
                            <br />
                            הייתי בת 21 אחרי צבא, עם חבר ראשון שהיה האהבה הראשונה שלי, ועבודה מאוד מכובדת בהייטק.
                            בצבא שירתתי בגולני וכבר אז שוייכתי לעולם המחשבים, הייתי מנהלת רשת מחשוב במשרד ובתרגילים בשטח וכמו כל חיילת טובה שובצתי גם לאין ספור תורניות מטבח ושמירות.<br />
                            ניתן לומר שהייתי הכל חוץ מלהיות אני, וכשאדם רחוק מעצמו אז הכל הופך להיות קשה.<br />
                            אחד מחבריי לגדוד שהיה ער למצבי אמר לי: "הבעיה שלך היא שאת תמיד חושבת שכולם נגדך"
                            לא הבנתי מה הוא רוצה ממני באותה תקופה, אבל משום מה המילים שלו לא עזבו אותי.
                            <br />
                            <br />
                            והנה אני אחרי הצבא בטוחה שמעכשיו הכל ישתפר... הרי יש לי אהבה ועבודה טובה עם שכר גבוה
                            אין לי על מה להתלונן, אבל עדיין משהו בי היה חסר.
                            אז החלטתי שזה הזמן לעשות טיול, לנקות את כל המחשבות ולהתרכז רק בלהנות וכמה שיותר.
                            וזה אכן מה שהיה, אבל מתישהו הטיול נגמר והשגרה חוזרת וסוחפת אותך איתה.
                            אז התקבלתי לתואר ראשון במדעי המחשב והוצאתי ציונים מאוד גבוהים, והצטיינתי בעבודה, והייתי מוקפת אנשים שלאט לאט הלכו והתרחקו ממני
                            ולא היה לי מושג למה.
                            עד שגם החבר שלי החליט לסיים את הקשר, הוא טען שקשה לו איתי, והסביר שזאת לגמרי אני ולא הוא.
                            <br />
                            <br />
                            <img src="~/images/gallery/MyStory/10.jpg" />
                            <br />
                            <br />
                            מאז הפרידה ממנו התחיל השינוי בחיי.<br />
                            בהתחלה הייתי בדיכאון, בקושי אכלתי ולא הצלחתי להתרכז בלימודים או בעבודה.<br />
                            גם את מעט החברים שנשארו סביבי לא רציתי לראות, הרגשתי לבד והחלטתי שאני צריכה להתנתק מהכל.<br />
                            אז התפטרתי מהעבודה, עזבתי את הלימודים ונסעתי לעשות מועדפת בערבה.<br />
                            חברה טובה הצטרפה אלי ועבדנו יחד במפעל לפלפלים.<br />
                            מהר מאוד פרחתי, התאהבתי בנוף המדהים של הדרום, באנשים ובשלווה שמשרה המקום לעומת המירוץ הקדחתני של המרכז.
                            העבודה הייתה אינטסיבית (12 שעות ביום) ומשעממת... אבל ידעתי שאני רוצה להשאר בדרום
                            ולכן התחלתי לחפש שם משהו אחר -
                            כך הגעתי לחוות הסוסים הראשונה שלי.
                            <br />
                            <br />
                            <img src="~/images/gallery/MyStory/9.jpg" />
                            <br />
                            <br />
                            הכל קרץ לי שם ומיד התמלאתי תשוקה וסקרנות לחיה המדהימה הזו , הכסף כבר אזל ולכן עבדתי שעות נוספות תמורת שיעורי רכיבה.
                            הייתה לי מטרה לדעת לזוז ולכוון את הסוס ימינה ושמאלה... עוד לא הבנתי כמה העולם הזה עמוק וכמה יש לו להראות לי וללמד אותי, דברים שלא ידעתי בכלל שאפשר ללמד.
                            אהבתי את החיים שלי, אהבתי לבוא לעבודה ולהריח את הריח של הסוסים, להאכיל אותם, לעשות להם מקלחת מרעננת בימים חמים.<br />
                            גלי בעלת החווה שילבה אותי לאט בעוד תחומים ונתנה לי לעזור לה כ"מובילה" בשיעורי הרכיבה שהעבירה,
                            לאחר זמן מה היא אמרה לי שהיא רואה בי הרבה מעבר והמליצה לי להכנס לקורס מדריכי רכיבה.
                            וכך היה... במקביל לקורס כדי לחוות מכל העולמות חיפשתי מאמן אישי לשיעורי רכיבה נוספים,
                            והגעתי ממש במקרה למאמן גדול בשם מאיר אליעבוש.
                            <br />
                            <br />
                            <img src="~/images/gallery/MyStory/7.jpg" />
                            <br />
                            <br />
                            בהתחלה מאיר לא רצה ללמד אותי, הוא אמר לי שאני לא מבינה כלום בסוסים. אבל זה לא שבר אותי
                            הייתי מגיעה רק כדי לראות אותו רוכב וכשהיה יורד מהסוס הייתי מציפה אותו בשאלות.
                            בדיאבד הוא אמר לי ששאלתי את השאלות הנכונות וזו הסיבה שלבסוף הוא השתכנע והסכים ללמד אותי.
                            <br />
                            <br />
                            מאיר לימד אותי מזה סוס, הוא לימד אותי מזה רכות והקשבה, איך אפשר לקבל כל כך הרבה כשבאים ממקום של רוגע אמיתי.
                            דרך הסוסים מצאתי את השלווה הנפשית שלי ופתאום הבנתי כמה הייתי רחוקה ממנה.
                            הייתי בנאדם חסר סבלנות, מתרגזת בקלות, לקחתי את כולם קשה כל כך והחיים הרגישו לי כמו ריב אחד גדול כל הזמן.
                            הבנתי שבאמת חשבתי והתנהגתי כאילו כולם נגדי, וזה למה התרחקו ממני.
                            <br />
                            הרבה פעמים ניסיתי להבין מה מיוחד כל כך ברכיבה ואיך דרכה מצאתי, קיבלתי והשלמתי עם עצמי.
                            איך התבהרו לי כל התובנות הללו?
                            איך הפכתי מאדם אגרסיבי ולא נעים לסביבה לאדם רגועה מוקף באנשים?
                            איך דרך הסוסים התחלתי לאהוב את מי שאני, להרגיש יפה ולדעת לקבל מחמאות.
                            <br />
                            <br />
                            <img src="~/images/gallery/MyStory/13.jpg" />
                            <br />
                            <br />
                            והבנתי,<br />
                            כשיש מישהו שאוהב אותך ומקבל אותך ומקשיב לך, אתה לומד לאהוב ולהקשיב לעצמך וגם לאחרים,
                            אתה מקבל את עצמך ומרגיש שלם, וכך הרבה יותר קל לנו לאהוב את עצמנו - כשיש מישהו אחר שמראה לנו את
                            הדברים הטובים שטמונים בנו.
                            הסוס הראה לי את הכל, הסוס קיבל אותי, ואהב אותי גם כשלא הצלחתי ולא הייתי מובנת לו. הוא
                            הקשיב וניסה שוב ולא התייאש ממני, נתן לי להרגיש בטוחה וברגע שעשיתי דבר נכון הוא דאג
                            להדגיש את זה ולתת חזרה.
                            דרך רכיבה נכונה ורגועה שדורשת הרבה הקשה וסבלנות אפשר להגיע להרמוניה עם הסוס. רק אחרי
                            שהתחלתי להיות בטוחה בעצמי ולאהוב את עצמי, אנשים אחרים למדו לאהוב אותי גם.<br />
                            הרבה מאוד חברים ראו את השינוי ואמרו לי כמה השתנתי לטובה, כמה שהם שמחים שאני
                            מבינה אותם ושהצלחתי לתקן את מה שהיה שבור.
                            הרכיבה הצילה לי את החיים.. והייתי רוצה שכולם יחוו את החוויה שאני עברתי.
                            לפעמים אנחנו כל כך שקועים בתוך מערבולת החיים ולא מבינים כמה אנחנו צריכים שינוי, כמה הנפש צריכה מנוחה.
                            הייתי רוצה שכולם ילמדו לרכב נכון כדי שיוכלו להגיע לשלווה נפשית, אושר ואהבה עצמית.
                            <br />
                            <br />
                           בהמשך דרכי המקצועית למדתי אצל מאמנים נוספים ונחשפתי ליכולות ושיטות אחרות, לא תמיד הסכמתי עם כולם אבל מכל אחד לקחתי משהו.
                            בניתי לעצמי תוכנית לימודית המשלבת רכיבה רגועה והרמונית יחד עם פיתוח יכולות לביצוע תרגילים מתקדמים וזכייה בתחרויות.
                            כאשר הדגש העיקרי הוא על הדרך שבסופו של דבר מובילה כשלעצמה לתוצאות, הן במישור הנפשי והן במישור המקצועי. <br/>
                            אני רוקאת לזה,
                            <a href="@Url.Action("SpiritualRiding", "RidingStyles")">רכיבה רוחנית.</a>
                            <br />
                            <br />
                            תודה שהקדשתם זמן לקרוא את סיפור חיי.
                        </p>
                    </div>
                    <div class="span4">

                        <!--sidebar------------------------------------------------->
                        <div class="sidebar">
                            <div class="widget">
                                <h2 class="title"><span>text widjet</span></h2>
                                <p>Praesent vestibulum molestie lacus. Aenean nonummy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi nascetur ridiculus mus. Nulla dui. Fusce feugiat malesuada odio. Morbi nunc odio, gravida at, cursus nec, luctus a, lorem. Maecenas tristique orci ac sem. Duis ultricies pharetra magna. Donec accumsan malesuada orci. Donec sit amet eros. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>
                                <p><a href="about.html" class="arrow_link">Read more</a></p>
                            </div>
                            <div class="widget">
                                <h2 class="title"><span>:מומלץ לקרוא גם</span></h2>
                                <ul class="recent_post">
                                    <li onclick="location.href='@Url.Action("SpiritualRiding", "RidingStyles")'">
                                        <img src="../images/gallery/Articles/sideBar/spiritualRiding.jpg" />
                                        <div><b>רכיבה רוחנית</b></div>
                                        <p dir="rtl">
                                            סגנון הרכיבה שלי קצת שונה משל אחרים, 
                                            ואני לא מדברת על התוצאה הסופית, אני מדברת על הדרך.....
                                        </p>
                                        <div class="clear"></div>
                                    </li>
                                    <li onclick="location.href='@Url.Action("Peaceful", "Articles")'">
                                        <img src="../images/gallery/Articles/sideBar/peaceful.jpg" />
                                        <div><b>שלווה נפשית </b></div>
                                        <p dir="rtl">
                                            מזה בכלל שלווה נפשית?
                                            לפעמים זה נשמע סתם כמו צמד מילים יפה.....
                                        </p>
                                        <div class="clear"></div>
                                    </li>
                                    <li>
                                        <a href="#"><img src="~/images/img10.jpg" alt="" /></a>
                                        <div><a href="#"> תחרויות </a></div>
                                        <div class="clear"></div>
                                    </li>
                                </ul>         
                            </div>
                            <!--//sidebar------------------------------------------------->
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>



@section ScriptEnd
{
    <script type="text/javascript">
        $(document).ready(function () {
            $("li").removeClass("current");
            $("#liMyStory").addClass("current");
        });
    </script>
}